apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: gtochess

build:
  local:
    push: false
    useBuildkit: true
  artifacts:
    - image: gtochess-api
      context: backend
      docker:
        dockerfile: Dockerfile
        target: runtime
        buildArgs:
          ENGINE_PLATFORM: linux-x86-64
    - image: gtochess-web
      context: frontend
      docker:
        dockerfile: Dockerfile
        target: runtime

manifests:
  kustomize:
    paths:
      - .kube/base

deploy:
  kubectl: {}

portForward:
  - resourceType: service
    resourceName: gtochess-web
    port: 80
    localPort: 5173
  - resourceType: service
    resourceName: gtochess-api
    port: 8000
    localPort: 8010

profiles:
  - name: api-only
    patches:
      - op: remove
        path: /build/artifacts/1
    manifests:
      kustomize:
        paths:
          - .kube/base
